name: scavenge_hunt
description: "Scavenge Hunt app. Owned by Bryce Meizen. Developed by Waqad, Saif, and Ahad"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
#  sdk: ^3.8.1
  sdk: ">=3.6.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.9.1
  google_fonts: ^6.3.1

  cached_network_image: ^3.4.1
  country_picker: ^2.0.27
  dropdown_button2: ^2.3.9
  easy_date_timeline: ^2.0.9
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.2.0
  gradient_borders: ^1.0.2
  percent_indicator: ^4.2.5
  pinput: ^5.0.1
  smooth_page_indicator: ^1.2.1
  video_player: ^2.10.0



  # State Management
  #  riverpod_annotation: ^2.6.1

  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  get: ^4.7.2 # temporary, until we replace its usage from UI
  go_router: ^14.7.1


#  flutter_riverpod: ^3.0.0-dev.17
#  riverpod_annotation: ^3.0.0-dev.17



  # Network calls
  dio: ^5.9.0

  # Location
  geolocator: ^14.0.2


  # Local Database
  drift: ^2.28.1
  drift_flutter: ^0.2.5
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5


  # Logging
  logger: ^2.6.1

  # Error Reporting
  sentry_flutter: ^9.6.0


  # Permissions
  permission_handler: ^12.0.1


  # Utils
  equatable: ^2.0.7 # Object equality checks
  intl: ^0.20.2 # date manipulation
  url_launcher: ^6.3.2 # for launching urls
  force_update_helper: ^0.2.1 # update helper

  # Shorebird
  shorebird_code_push: ^2.0.4


  # app-configuration
  package_rename: ^1.10.0
  flutter_launcher_icons: ^0.14.4


dev_dependencies:
  sentry_dart_plugin: ^3.1.1
  flutter_test:
    sdk: flutter

  drift_dev: ^2.28.1
  build_runner: ^2.7.0
  custom_lint: ^0.8.0
#  riverpod_generator: ^3.0.0-dev.17
#  riverpod_lint: ^3.0.0-dev.17


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - shorebird.yaml
    - assets/images/
    - assets/icons/
#    - assets/fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Black.ttf
          weight: 900
        - asset: assets/fonts/Nunito/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito/Nunito-ExtraLight.ttf
          weight: 200

    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka/Fredoka-Bold.ttf
          weight: 700
        - asset: assets/fonts/Fredoka/Fredoka-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Fredoka/Fredoka-Medium.ttf
          weight: 500
        - asset: assets/fonts/Fredoka/Fredoka-Regular.ttf
          weight: 400
        - asset: assets/fonts/Fredoka/Fredoka-Light.ttf
          weight: 300

flutter_assets:
  assets_path: assets/images/
  output_path: lib/constants/
  filename: app_images.dart
  field_prefix: ''

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: scavenge
  org: scavenge-app
